### ISSUE TITLE
README

### ISSUE THREAD

**Issue by DarkGuardsman** [Dennisbonke/VoltzEngine1.8#1]
I rather you have forked the repo than just cloned it. Plus this counts as redistributing the code as Voltz Engine is not fully open source. I'll give you a few days to either fork it correctly or take this down. If you don't then i'll notify github and provide a DMCA violation.

https://github.com/BuiltBrokenModding/VoltzEngine/blob/development/license.md

**Comment by Dennisbonke** [comment]
Ok, will do Today or Tomorrow. I will fork it then.
